@include('components.navbar.index')
@include('components.hero-section.index')
@include('components.quick-action-cards.index')
@include('components.profile-section.index')
@include('components.news-section.index')
@include('components.emails.contact')
@include('components.footer.index')
